services:
  postgres:
    image: 'postgres:16'
    container_name: gardenassistant-postgres
    environment:
      - 'POSTGRES_DB=gardenassistantdb'
      - 'POSTGRES_PASSWORD=admin123'
      - 'POSTGRES_USER=gardenAdmin'
    ports:
      - '5434:5432'
    volumes:
      - gardenassistant-postgres-data:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    container_name: gardenassistant-redis
    ports:
      - '6379:6379'
  app:
    image: 'gardenassistant'
    container_name: gardenassistant-app
    ports:
      - '9090:9090'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gardenassistantdb
      - SPRING_DATASOURCE_USERNAME=gardenAdmin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

volumes:
  gardenassistant-postgres-data:
