type Garden{
    id : ID!
    name : String!
    description : String
    location : String!
    maxPlants : Int!
    plants : [Plant!]!
}

type Plant {
    id: ID!
    name: String!
    plantProfile: PlantProfile
    status: String!
}

type PlantProfile{
    id : ID!
    name : String!
    wateringFrequencyDays : Int
    minTemperature : Float
    maxTemperature : Float
    likesRain : Boolean
}

type GardenRecommendation{
    type : String!
    severity : String!
    message : String
}

type PlantRecommendation{
    plantId: ID!
    plantName: String!
    type: String!
    severity: String!
    message: String!
}

type Query{
    myGardens(page : Int!, size : Int!): GardenPage!
    checkWeatherForGarden(gardenId : ID!) : Weather!
    gardenRecommendation(gardenId : ID!) : GardenRecommendation!
    plantProfiles: [PlantProfile!]!
    getPlantRecommendation(gardenId : ID!) : [PlantRecommendation!]!
}

type GardenPage{
    content : [Garden!]!
    totalElements : Int!
    totalPages : Int!
    currentPage : Int!
}

input CreateGardenRequest{
    name : String!
    description : String
    location : String!
    maxPlants : Int!
}

input CreatePlantRequest{
    name : String!
    plantProfileId: ID!
}
type PlantResponse{
    id: ID!
    name: String!
    plantProfile: PlantProfile
    status: String!
}


type Mutation{
    createGarden(gardenRequest : CreateGardenRequest!) : Garden!
    addPlant(gardenId : ID!, plantRequest : CreatePlantRequest!) : PlantResponse!
    removePlant(plantId : ID!) : Boolean!
    generateGardenReport : String
    waterPlant(plantId: ID!): Boolean!
    waterGarden(gardenId: ID!): Boolean!
}